package org.jbpm.evaluation.carinsurance
       
rule "risk for young drivers" 
ruleflow-group "testCalc"
dialect "mvel" 
when
 	driver : Driver( age < 50)
 	policy : Policy() 
then   
	System.out.println( "I have a young driver, his name is: " + driver.driverName + " and my age is: " + driver.age);
	
	driver.creditScore = 99;
	policy.driverRisk = 99; 
end 

rule "risk for old drivers" 
ruleflow-group "testCalc"
dialect "mvel" 
when
 	driver : Driver( age >= 50)
 	policy : Policy() 
then   
	System.out.println( "I have a old driver, his name is: " + driver.driverName + " and my age is: " + driver.age);
	 
	driver.creditScore = 0;  
	policy.driverRisk = 0; 
end 

